config/routes.rb
Rails.application.routes.draw do

  get 'applications/new'

  get 'jobs/new'

  get 'companies/new'
  get 'sessions/new'
  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'static_pages#signup'
  get "/signup/recruiter", to: 'recruiters#new'
  get "/signup/job_seeker", to: 'job_seekers#new'
  post "/signup/job_seeker", to: 'job_seekers#create'
  post "/signup/recruiter",  to: 'recruiters#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :recruiters do
    member do
      post 'update_company_id'
    end
  end
  resources :companies
  resources :job_seekers
  resources :jobs
  resources :applications
  resources :admins, only:[:edit, :update,:show]
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :recruiters
  has_many :jobs,dependent: :destroy

  VALID_URL_REGEX=/((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[\w]*))?)/i
  validates :name, presence: true, length: { maximum: 255 }
  validates :website, presence: true, length: { maximum: 255 }, format: { with: VALID_URL_REGEX }
  validates :headquarters, presence: true, length: { maximum: 255 }
  validates :size, presence: true, length: { maximum: 255 }
  validates :founded, presence: true
  validates :industry, presence: true, length: { maximum: 255 }
  validates :revenue, presence: true, length: { maximum: 255 }
  validates :synopsis, presence: true, length: { maximum: 2000 }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
    @company=Company.new
  end
  def index
    @companies = Company.paginate(page: params[:page])
  end
  def show
    @company = Company.find(params[:id])
  end


def edit
  @company = Company.find(params[:id])
end

def create
  @company=Company.new(company_params)
  if @company.save
    redirect_to @company
  else
    render 'new'
  end
end

def update
  @company = Company.find(params[:id])
  if @company.update_attributes(company_params)
    flash[:success] = "Company information updated"
    redirect_to @company
  else
    render 'new'
  end
end

def destroy
  Company.find(params[:id]).destroy
  flash[:success] = "Company deleted"
  redirect_to companies_url
end

private
def company_params
  params.require(:company).permit(:name,:website,:headquarters,:size,:founded,:industry,:revenue,:synopsis)
end

end

app/helpers/companies_helper.rb
module CompaniesHelper
# 返回指定用户的 Gravatar
  def gravatar_for_company(company,  size: 80 )
    gravatar_id = Digest::MD5::hexdigest(company.website.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: company.name, class: "gravatar")
  end

end

app/views/companies/_company.html.erb
<li>
  <%= gravatar_for_company company, size: 50 %>
  <%= link_to company.name, company %>

  <% if admin?%>
    | <%= link_to "edit", edit_company_path(company)%>
  <% end %>

  <% if admin?%>
    | <%= link_to "delete", company, method: :delete,
                  data: { confirm: "You sure?" } %>
  <% end %>
  <% if recruiter?&&join_company?%>
    | <%= link_to("join", update_company_id_recruiter_path(current_user,:real_company_id=>company.id), :method => :post,
                  data:{:confirm => "Join this company?"})%>
  <% end %><br/>
  <span class="job"><span style="display:inline-block; width:20px"></span>Company id: <%=company.id %></span>
</li>

app/views/companies/_error_messages.html.erb
<% if @company.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@company.errors.count, "error") %>.
    </div>
    <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <%= render 'error_messages' %>
  <%= f.label :name %>
  <%= f.text_field :name,class: 'form-control' %>
  <%= f.label :website %>
  <%= f.text_field :website ,class: 'form-control'%>
  <%= f.label :headquarters %>
  <%= f.text_field :headquarters ,class: 'form-control'%>
  <%= f.label :size %>
  <%= f.text_field :size,class: 'form-control' %>
  <%= f.label :founded %>
  <%= f.text_field :founded ,class: 'form-control'%>
  <%= f.label :industry %>
  <%= f.text_field :industry,class: 'form-control' %>
  <%= f.label :revenue %>
  <%= f.text_field :revenue,class: 'form-control' %>
  <%= f.label :synopsis %>
  <%= f.text_field :synopsis,class: 'form-control' %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/companies/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:button_text, 'Save changes') %>
<h1>Edit the information</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for_company @company %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/companies/index.html.erb
<% provide(:title, 'All Companies') %>
<h1>All Companies</h1>

<% if recruiter?||admin?%>
  <div class="add_button">
    <%= link_to "Add", companies_new_path, class: "btn btn-lg btn-primary" %>&nbsp&nbsp
    <% if recruiter?%>
      <%= link_to "My conpany", current_user ,class: "btn btn-info"%>
    <% end %>
  </div>
<% end %>

<%= will_paginate %>

<ul class="companies">
  <%= render @companies %>
</ul>

<%= will_paginate %>

app/views/companies/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Create a company</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/companies/show.html.erb
<% provide(:title, @company.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for_company @company %>
        <br/><br/><br/><br/><br/><br/>
        Name:<%= @company.name %><br/><br/>
        Website: <%= @company.website %><br/><br/>
        Headquarter: <%= @company.headquarters %><br/><br/>
        Employee: <%= @company.size %><br/><br/>
        Founded: <%= @company.founded %><br/><br/>
        Industry: <%= @company.industry %><br/><br/>
        Revenue: <%= @company.revenue %><br/><br/>
        Synopsis: <%= @company.synopsis %><br/><br/>
      </h1>
    </section>
  </aside>
</div>