config/routes.rb
Rails.application.routes.draw do

  get 'applications/new'

  get 'jobs/new'

  get 'companies/new'
  get 'sessions/new'
  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'static_pages#signup'
  get "/signup/recruiter", to: 'recruiters#new'
  get "/signup/job_seeker", to: 'job_seekers#new'
  post "/signup/job_seeker", to: 'job_seekers#create'
  post "/signup/recruiter",  to: 'recruiters#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :recruiters do
    member do
      post 'update_company_id'
    end
  end
  resources :companies
  resources :job_seekers
  resources :jobs
  resources :applications
  resources :admins, only:[:edit, :update,:show]
end

app/models/recruiter.rb
class Recruiter < ApplicationRecord
  belongs_to :company, optional: true
  before_save { email.downcase! }
  # default_scope -> { order(created_at: :desc) }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def Recruiter.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController
  before_action :logged_in_user, only: [:index,:edit, :update,:show, :update_company_id]
  before_action :correct_user,   only: [:edit, :update, :update_company_id]
  before_action :must_be_admin,  only: [:destroy]
  include SessionsHelper

  def index
    @recruiters = Recruiter.paginate(page: params[:page])
  end
  def new
    @recruiter = Recruiter.new
  end
  def show
    @recruiter = Recruiter.find(params[:id])
  end
  def create
    @recruiter = Recruiter.new(recruiter_params)
    if @recruiter.save
      log_in @recruiter,'Recruiter' unless admin?
      flash[:success] = "Welcome to the JALAPENO!"
      redirect_to @recruiter
    else
      render 'new'
    end
  end
  def edit
    @recruiter = Recruiter.find(params[:id])
  end

  def update
    @recruiter = Recruiter.find(params[:id])
    if @recruiter.update_attributes(recruiter_params)
      flash[:success] = "Profile updated"
      redirect_to @recruiter
    else
      render 'edit'
    end
  end
  def destroy
    Recruiter.find(params[:id]).destroy
    flash[:success] = "Recruiter deleted"
    redirect_to recruiters_url
  end

  def update_company_id
    @recruiter = Recruiter.find params[:id]
    @recruiter.update_attributes(company_id:params[:real_company_id])
    redirect_to @recruiter
  end

  private
  def recruiter_params
    params.require(:recruiter).permit(:name, :email, :password, :password_confirmation)
  end
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
  def correct_user
    @recruiter = Recruiter.find(params[:id])
    redirect_to(root_url) unless @recruiter == current_user||admin?
  end
  def must_be_admin
    unless admin?
      flash[:danger] = "Not allowed!"
      redirect_to(root_url)
    end
  end
end

app/helpers/recruiters_helper.rb
module RecruitersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for_recruiter(recruiter, size: 80)
    gravatar_id = Digest::MD5::hexdigest(recruiter.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: recruiter.name, class: "gravatar")
  end
end

app/views/recruiters/_error_messages.html.erb
<% if @recruiter.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@recruiter.errors.count, "error") %>.
    </div>
    <ul>
      <% @recruiter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/recruiters/_form.html.erb
<%= form_for(@recruiter) do |f| %>
  <%= render 'error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>


  <% unless admin?%>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  <% end %>

  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/recruiters/_recruiter.html.erb
<li>
  <%= gravatar_for_recruiter recruiter, size: 50 %>
  <%= link_to recruiter.name, recruiter %>

  <% if admin?%>
    | <%= link_to "edit", edit_recruiter_path(recruiter)%>
  <% end %>

  <% if admin?%>
    | <%= link_to "delete", recruiter, method: :delete,
                  data: { confirm: "You sure?" } %>
  <% end %>

</li>

app/views/recruiters/edit.html.erb
<% provide(:title, "Edit profile") %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@recruiter) do |f| %>
      <%= render 'error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>


      <% unless admin?%>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      <% end %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
    <div class="gravatar_edit">
      <%= gravatar_for @recruiter %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/recruiters/index.html.erb
<% provide(:title, 'All recruiters') %>
<h1>All recruiters</h1>
<div class="add_button">
  <%= link_to "Add", signup_recruiter_path, class: "btn btn-lg btn-primary" %>
</div>
<%= will_paginate %>
<ul class="recruiters">
  <%= render @recruiters %>
</ul>
<%= will_paginate %>

app/views/recruiters/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up as a recruiter</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@recruiter) do |f| %>
      <%= render 'error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/recruiters/show.html.erb
<% provide(:title, @recruiter.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <div class="profile_identity">
        <%= gravatar_for_recruiter @recruiter %>
          recruiter
        </div>
        <br/><br/><br/><br/>
        Name:  <%= @recruiter.name %><br/><br/>
        Email:  <%= @recruiter.email %><br/><br/>
        Company: <%= @recruiter.company_id %>
        <% if recruiter?%>
          <% if join_company?%>
             <%= link_to " choose a company", companies_path%>
          <% else %>
            <%= link_to "show", @recruiter.company %>
            | <%= link_to "edit", edit_company_path(@recruiter.company)%>
            | <%= link_to("quit", update_company_id_recruiter_path(current_user,:real_company_id=>nil), :method => :post,
                          data:{:confirm => "Quit this company?"})%>
          <% end %>
        <% end %>
      </h1>
    </section>
  </aside>
</div>